"""FMP-specific target engineering."""

from quant_warehouse.platforms.data_providers.fmp.target_engineering.labels import (
    add_action_labels,
    add_binary_classification_labels,
    add_rank_regression_labels,
    build_label_panel,
    build_oracle_labels,
    build_trade_results,
    deduplicate_labels,
    generate_optimal_events,
)
from quant_warehouse.platforms.data_providers.fmp.target_engineering.hits import (
    HitsLabelSpec,
    build_hits_labels,
    build_hold_timing_hits_labels,
    build_inverse_holding_time_hits_labels,
    build_return_and_speed_hits_labels,
)
from quant_warehouse.platforms.data_providers.fmp.target_engineering.macro_events import (
    MACRO_RESPONSE_CLASSES,
    MacroEventSpec,
    build_macro_event_label_panel,
    build_macro_event_targets,
    build_macro_family_label_panel,
    build_macro_response_labels,
    deduplicate_binary_label_columns,
    normalize_macro_events,
)
from quant_warehouse.platforms.data_providers.fmp.target_engineering.constituents import (
    EVENT_COLUMNS as HISTORICAL_CONSTITUENT_EVENT_COLUMNS,
    SUB_SECTOR_TARGET_COLUMN,
    build_historical_constituent_event_label_panel,
    build_historical_sub_sector_target_panel,
)
from quant_warehouse.platforms.data_providers.fmp.target_engineering.operations import (
    apply_trade_deduplication,
    build_label_rows_from_completed_trades,
    build_label_statistics,
    trade_return_pct,
)
from quant_warehouse.platforms.data_providers.fmp.target_engineering.returns import (
    build_cross_sectional_rank_labels,
    build_forward_return_labels,
)
from quant_warehouse.platforms.data_providers.fmp.target_engineering.specs import (
    LabelBuildSpec,
    OracleLabelResult,
    TradeGenerationResult,
    parse_k_list,
)
from quant_warehouse.platforms.data_providers.fmp.target_engineering.strategy_solver import (
    Trade,
    solve_longs_by_frequency,
    solve_optimal_trades_generic,
    solve_shorts_by_frequency,
    solve_side_trades_by_frequency_batched_multi_k,
    solve_trades_by_frequency,
)
from quant_warehouse.platforms.data_providers.fmp.target_engineering.target_families import (
    ANALYST_RATING_TARGET_FAMILY,
    DIVIDEND_TARGET_FAMILY,
    EARNINGS_REPORT_TARGET_FAMILY,
    FILING_TARGET_FAMILY,
    GOVERNMENT_TRADING_TARGET_FAMILY,
    INSIDER_TRADING_TARGET_FAMILY,
    PRICE_TARGET_TARGET_FAMILY,
    SPLIT_TARGET_FAMILY,
    STOCK_GRADES_TARGET_FAMILY,
    TARGET_FAMILY_REGISTRY,
    TargetFamilySpec,
    get_target_family,
)

__all__ = [
    "LabelBuildSpec",
    "HitsLabelSpec",
    "OracleLabelResult",
    "Trade",
    "TradeGenerationResult",
    "add_action_labels",
    "add_binary_classification_labels",
    "add_rank_regression_labels",
    "apply_trade_deduplication",
    "build_cross_sectional_rank_labels",
    "build_forward_return_labels",
    "build_hits_labels",
    "build_hold_timing_hits_labels",
    "build_inverse_holding_time_hits_labels",
    "build_return_and_speed_hits_labels",
    "HISTORICAL_CONSTITUENT_EVENT_COLUMNS",
    "SUB_SECTOR_TARGET_COLUMN",
    "build_historical_constituent_event_label_panel",
    "build_historical_sub_sector_target_panel",
    "MACRO_RESPONSE_CLASSES",
    "MacroEventSpec",
    "build_macro_event_label_panel",
    "build_macro_event_targets",
    "build_macro_family_label_panel",
    "build_macro_response_labels",
    "deduplicate_binary_label_columns",
    "normalize_macro_events",
    "build_label_panel",
    "build_label_rows_from_completed_trades",
    "build_label_statistics",
    "build_oracle_labels",
    "build_trade_results",
    "deduplicate_labels",
    "generate_optimal_events",
    "parse_k_list",
    "solve_longs_by_frequency",
    "solve_optimal_trades_generic",
    "solve_shorts_by_frequency",
    "solve_side_trades_by_frequency_batched_multi_k",
    "solve_trades_by_frequency",
    "trade_return_pct",
    "INSIDER_TRADING_TARGET_FAMILY",
    "ANALYST_RATING_TARGET_FAMILY",
    "DIVIDEND_TARGET_FAMILY",
    "EARNINGS_REPORT_TARGET_FAMILY",
    "FILING_TARGET_FAMILY",
    "GOVERNMENT_TRADING_TARGET_FAMILY",
    "PRICE_TARGET_TARGET_FAMILY",
    "SPLIT_TARGET_FAMILY",
    "STOCK_GRADES_TARGET_FAMILY",
    "TARGET_FAMILY_REGISTRY",
    "TargetFamilySpec",
    "get_target_family",
]
