"""Target engineering utilities for labels and oracle trade targets."""

from quant_warehouse.target_engineering.labels import (
    add_action_labels,
    add_binary_classification_labels,
    add_rank_regression_labels,
    build_label_panel,
    build_oracle_labels,
    build_trade_results,
    deduplicate_labels,
    generate_optimal_events,
)
from quant_warehouse.target_engineering.event_pairs import (
    EVENT_PAIR_COLUMNS,
    EVENT_PAIR_LIBRARY,
    EVENT_PAIR_SECTION,
    EVENT_PAIR_TAXONOMY,
    EventPairLoadResult,
    EventPairStore,
    build_event_pairs_from_historical_data,
    fetch_fmp_event_pair_family,
    fetch_fmp_event_pairs,
    get_event_side,
    get_mirror_event_type,
    normalize_event_pairs,
)
from quant_warehouse.target_engineering.optimal_trades import build_optimal_trade_labels
from quant_warehouse.target_engineering.option_labels import (
    OptionLabelResult,
    OptionLabelSpec,
    build_option_label_panel,
    build_option_labels,
    compute_return_covariance_matrix,
    solve_long_only_mean_variance_weights,
    solve_mean_variance_weights,
)
from quant_warehouse.target_engineering.options import (
    build_option_best_return_labels,
    build_option_mean_variance_labels,
    build_option_return_rank_labels,
)
from quant_warehouse.target_engineering.returns import (
    build_cross_sectional_rank_labels,
    build_forward_return_labels,
)
from quant_warehouse.target_engineering.option_dataset import (
    OptionMlDatasetResult,
    OptionMlDatasetSpec,
    build_option_ml_dataset,
    save_option_ml_dataset,
)
from quant_warehouse.target_engineering.thetadata_loader import (
    OPTIONS_THETADATA_EOD_LIBRARY,
    ThetaDataDownloadSpec,
    download_option_snapshots_for_range,
    load_cached_snapshots_for_trade_window,
    load_thetadata_option_snapshots,
    normalize_thetadata_option_chain,
    option_chain_range_cached,
    option_chain_snapshots_cached,
    read_option_chain_arctic,
    write_option_chain_arctic,
)
from quant_warehouse.target_engineering.operations import (
    apply_trade_deduplication,
    build_label_rows_from_completed_trades,
    build_label_statistics,
    trade_return_pct,
)
from quant_warehouse.target_engineering.specs import (
    LabelBuildSpec,
    OracleLabelResult,
    TradeGenerationResult,
    parse_k_list,
)
from quant_warehouse.target_engineering.strategy_solver import (
    Trade,
    solve_joint_trade_sequence_by_frequency,
    solve_joint_trades_by_frequency,
    solve_longs_by_frequency,
    solve_optimal_joint_trade_sequence_generic,
    solve_optimal_joint_trades_generic,
    solve_optimal_trades_generic,
    solve_shorts_by_frequency,
    solve_trades_by_frequency,
)

__all__ = [
    "LabelBuildSpec",
    "OracleLabelResult",
    "EVENT_PAIR_COLUMNS",
    "EVENT_PAIR_LIBRARY",
    "EVENT_PAIR_SECTION",
    "EVENT_PAIR_TAXONOMY",
    "EventPairLoadResult",
    "EventPairStore",
    "OptionLabelResult",
    "OptionLabelSpec",
    "OptionMlDatasetResult",
    "OptionMlDatasetSpec",
    "OPTIONS_THETADATA_EOD_LIBRARY",
    "ThetaDataDownloadSpec",
    "Trade",
    "TradeGenerationResult",
    "add_action_labels",
    "add_binary_classification_labels",
    "add_rank_regression_labels",
    "apply_trade_deduplication",
    "build_label_panel",
    "build_label_rows_from_completed_trades",
    "build_label_statistics",
    "build_cross_sectional_rank_labels",
    "build_event_pairs_from_historical_data",
    "build_forward_return_labels",
    "build_oracle_labels",
    "build_optimal_trade_labels",
    "build_option_best_return_labels",
    "build_option_label_panel",
    "build_option_labels",
    "build_option_mean_variance_labels",
    "build_option_ml_dataset",
    "build_option_return_rank_labels",
    "build_trade_results",
    "download_option_snapshots_for_range",
    "fetch_fmp_event_pair_family",
    "fetch_fmp_event_pairs",
    "load_cached_snapshots_for_trade_window",
    "option_chain_range_cached",
    "option_chain_snapshots_cached",
    "read_option_chain_arctic",
    "save_option_ml_dataset",
    "compute_return_covariance_matrix",
    "solve_long_only_mean_variance_weights",
    "solve_mean_variance_weights",
    "deduplicate_labels",
    "generate_optimal_events",
    "get_event_side",
    "get_mirror_event_type",
    "normalize_event_pairs",
    "parse_k_list",
    "load_thetadata_option_snapshots",
    "solve_joint_trade_sequence_by_frequency",
    "solve_joint_trades_by_frequency",
    "solve_longs_by_frequency",
    "solve_optimal_joint_trade_sequence_generic",
    "solve_optimal_joint_trades_generic",
    "solve_optimal_trades_generic",
    "solve_shorts_by_frequency",
    "solve_trades_by_frequency",
    "normalize_thetadata_option_chain",
    "trade_return_pct",
    "write_option_chain_arctic",
]
