"""Research utilities for exploratory Quant Warehouse notebooks."""

from quant_warehouse.research_tools.event_feature_dataset import (
    EventFeatureDatasetConfig,
    EventFeatureDatasetResult,
    FMP_EVENT_CONTEXT_FEATURE_FAMILIES,
    add_fmp_event_context_feature_families,
    build_event_context,
    build_event_feature_text_dataset,
    build_identity_text_dataset,
    event_pair_task_specs,
    feature_family_text,
    fmp_event_context_allowed_feature_families_by_task,
    oracle_side_task_specs,
    sanitize_task_name,
)
from quant_warehouse.research_tools.feature_family_eval import (
    FamilyEvaluationConfig,
    FeatureSpec,
    build_fundamental_feature_panel,
    cap_features_by_quality,
    evaluate_feature_families,
    screen_fmp_equity_universe,
)
from quant_warehouse.research_tools.target_family_eval import (
    BinaryTargetConfig,
    build_event_target_panel,
    build_oracle_trade_target_panel,
    combine_target_panels,
    evaluate_feature_target_matrix,
    load_fmp_event_pairs,
    summarize_binary_targets,
)

__all__ = [
    "BinaryTargetConfig",
    "EventFeatureDatasetConfig",
    "EventFeatureDatasetResult",
    "FMP_EVENT_CONTEXT_FEATURE_FAMILIES",
    "add_fmp_event_context_feature_families",
    "FamilyEvaluationConfig",
    "FeatureSpec",
    "build_event_context",
    "build_event_feature_text_dataset",
    "build_event_target_panel",
    "build_fundamental_feature_panel",
    "build_identity_text_dataset",
    "build_oracle_trade_target_panel",
    "cap_features_by_quality",
    "combine_target_panels",
    "event_pair_task_specs",
    "evaluate_feature_families",
    "evaluate_feature_target_matrix",
    "feature_family_text",
    "fmp_event_context_allowed_feature_families_by_task",
    "load_fmp_event_pairs",
    "oracle_side_task_specs",
    "sanitize_task_name",
    "screen_fmp_equity_universe",
    "summarize_binary_targets",
]
